// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1) {
  return window['go']['main']['App']['AddAccount'](arg1);
}

export function AddProvider(arg1) {
  return window['go']['main']['App']['AddProvider'](arg1);
}

export function ClearAllSessions() {
  return window['go']['main']['App']['ClearAllSessions']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CreateSession(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2, arg3, arg4);
}

export function DebugDumpState() {
  return window['go']['main']['App']['DebugDumpState']();
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteApiKey(arg1) {
  return window['go']['main']['App']['DeleteApiKey'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function ExportLogs(arg1) {
  return window['go']['main']['App']['ExportLogs'](arg1);
}

export function GenerateApiKey(arg1) {
  return window['go']['main']['App']['GenerateApiKey'](arg1);
}

export function GetAccountById(arg1, arg2) {
  return window['go']['main']['App']['GetAccountById'](arg1, arg2);
}

export function GetAccounts(arg1) {
  return window['go']['main']['App']['GetAccounts'](arg1);
}

export function GetAccountsByProviderId(arg1, arg2) {
  return window['go']['main']['App']['GetAccountsByProviderId'](arg1, arg2);
}

export function GetActiveSessions() {
  return window['go']['main']['App']['GetActiveSessions']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetErrorLogs(arg1) {
  return window['go']['main']['App']['GetErrorLogs'](arg1);
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetLogsByLevel(arg1, arg2) {
  return window['go']['main']['App']['GetLogsByLevel'](arg1, arg2);
}

export function GetOAuthAuthURL(arg1) {
  return window['go']['main']['App']['GetOAuthAuthURL'](arg1);
}

export function GetProviderById(arg1) {
  return window['go']['main']['App']['GetProviderById'](arg1);
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetProxyStatistics() {
  return window['go']['main']['App']['GetProxyStatistics']();
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetStatistics() {
  return window['go']['main']['App']['GetStatistics']();
}

export function GetStorePath() {
  return window['go']['main']['App']['GetStorePath']();
}

export function GetSupportedOAuthProviders() {
  return window['go']['main']['App']['GetSupportedOAuthProviders']();
}

export function HandleOAuthCallback(arg1, arg2) {
  return window['go']['main']['App']['HandleOAuthCallback'](arg1, arg2);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function LogCustomMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogCustomMessage'](arg1, arg2, arg3);
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function NavigateWindow(arg1) {
  return window['go']['main']['App']['NavigateWindow'](arg1);
}

export function OAuthLoginWithToken(arg1, arg2) {
  return window['go']['main']['App']['OAuthLoginWithToken'](arg1, arg2);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function RefreshOAuthToken(arg1, arg2) {
  return window['go']['main']['App']['RefreshOAuthToken'](arg1, arg2);
}

export function SetWindowTitle(arg1) {
  return window['go']['main']['App']['SetWindowTitle'](arg1);
}

export function ShowMessageDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowMessageDialog'](arg1, arg2, arg3);
}

export function ShowOpenDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowOpenDialog'](arg1, arg2);
}

export function ShowSaveDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowSaveDialog'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartOAuthLogin(arg1, arg2) {
  return window['go']['main']['App']['StartOAuthLogin'](arg1, arg2);
}

export function StartProxy(arg1, arg2) {
  return window['go']['main']['App']['StartProxy'](arg1, arg2);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}

export function UpdateAccount(arg1, arg2) {
  return window['go']['main']['App']['UpdateAccount'](arg1, arg2);
}

export function UpdateAccountCredentials(arg1, arg2) {
  return window['go']['main']['App']['UpdateAccountCredentials'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateConfigStruct(arg1) {
  return window['go']['main']['App']['UpdateConfigStruct'](arg1);
}

export function UpdateProvider(arg1, arg2) {
  return window['go']['main']['App']['UpdateProvider'](arg1, arg2);
}

export function ValidateOAuthToken(arg1, arg2) {
  return window['go']['main']['App']['ValidateOAuthToken'](arg1, arg2);
}
