// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CreateAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateAccount'](arg1, arg2, arg3);
}

export function CreateModelMapping(arg1) {
  return window['go']['main']['App']['CreateModelMapping'](arg1);
}

export function CreateProvider(arg1) {
  return window['go']['main']['App']['CreateProvider'](arg1);
}

export function CreateSession(arg1, arg2) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function GetAccountsByProvider(arg1) {
  return window['go']['main']['App']['GetAccountsByProvider'](arg1);
}

export function GetAllAccounts() {
  return window['go']['main']['App']['GetAllAccounts']();
}

export function GetAllProviders() {
  return window['go']['main']['App']['GetAllProviders']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetModelMappings() {
  return window['go']['main']['App']['GetModelMappings']();
}

export function GetProvider(arg1) {
  return window['go']['main']['App']['GetProvider'](arg1);
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function GetRequestLogs(arg1, arg2) {
  return window['go']['main']['App']['GetRequestLogs'](arg1, arg2);
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetStatistics() {
  return window['go']['main']['App']['GetStatistics']();
}

export function StartProxy(arg1, arg2) {
  return window['go']['main']['App']['StartProxy'](arg1, arg2);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function UpdateAccount(arg1, arg2) {
  return window['go']['main']['App']['UpdateAccount'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateModelMapping(arg1, arg2) {
  return window['go']['main']['App']['UpdateModelMapping'](arg1, arg2);
}

export function UpdateProvider(arg1, arg2) {
  return window['go']['main']['App']['UpdateProvider'](arg1, arg2);
}

export function UpdateSession(arg1, arg2) {
  return window['go']['main']['App']['UpdateSession'](arg1, arg2);
}
