// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {logger} from '../models';
import {proxy} from '../models';
import {oauth} from '../models';

export function AddAccount(arg1:types.Account):Promise<string>;

export function AddProvider(arg1:types.Provider):Promise<string>;

export function ClearAllSessions():Promise<void>;

export function ClearLogs():Promise<boolean>;

export function CreateSession(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>):Promise<types.SessionRecord>;

export function DebugDumpState():Promise<string>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DeleteApiKey(arg1:string):Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function ExportLogs(arg1:string):Promise<string>;

export function GenerateApiKey(arg1:string):Promise<types.ApiKey>;

export function GetAccountById(arg1:string,arg2:boolean):Promise<types.Account>;

export function GetAccounts(arg1:boolean):Promise<Array<types.Account>>;

export function GetAccountsByProviderId(arg1:string,arg2:boolean):Promise<Array<types.Account>>;

export function GetActiveSessions():Promise<Array<types.SessionRecord>>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetConfig():Promise<types.AppConfig>;

export function GetErrorLogs(arg1:number):Promise<Array<logger.LogEntry>>;

export function GetLogs(arg1:logger.LogOptions):Promise<logger.PaginatedResult>;

export function GetLogsByLevel(arg1:string,arg2:number):Promise<Array<logger.LogEntry>>;

export function GetOAuthAuthURL(arg1:string):Promise<string>;

export function GetProviderById(arg1:string):Promise<types.Provider>;

export function GetProviders():Promise<Array<types.Provider>>;

export function GetProxyStatistics():Promise<proxy.Statistics>;

export function GetProxyStatus():Promise<proxy.ProxyStatus>;

export function GetRecentLogs(arg1:number):Promise<Array<logger.LogEntry>>;

export function GetStatistics():Promise<logger.PersistentStatistics>;

export function GetStorePath():Promise<string>;

export function GetSupportedOAuthProviders():Promise<Array<string>>;

export function HandleOAuthCallback(arg1:string,arg2:string):Promise<oauth.OAuthResult>;

export function HideWindow():Promise<boolean>;

export function LogCustomMessage(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function MinimizeWindow():Promise<boolean>;

export function NavigateWindow(arg1:string):Promise<boolean>;

export function OAuthLoginWithToken(arg1:string,arg2:string):Promise<oauth.OAuthResult>;

export function OpenExternal(arg1:string):Promise<boolean>;

export function RefreshOAuthToken(arg1:string,arg2:Record<string, string>):Promise<oauth.TokenValidationResult>;

export function SetWindowTitle(arg1:string):Promise<boolean>;

export function ShowMessageDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ShowOpenDialog(arg1:string,arg2:string):Promise<string>;

export function ShowSaveDialog(arg1:string,arg2:string):Promise<string>;

export function ShowWindow():Promise<boolean>;

export function StartOAuthLogin(arg1:string,arg2:string):Promise<oauth.OAuthResult>;

export function StartProxy(arg1:number,arg2:string):Promise<boolean>;

export function StopProxy():Promise<boolean>;

export function ToggleWindow():Promise<boolean>;

export function UpdateAccount(arg1:string,arg2:types.Account):Promise<void>;

export function UpdateAccountCredentials(arg1:string,arg2:Record<string, string>):Promise<void>;

export function UpdateConfig(arg1:Record<string, any>):Promise<void>;

export function UpdateConfigStruct(arg1:types.AppConfig):Promise<void>;

export function UpdateProvider(arg1:string,arg2:types.Provider):Promise<void>;

export function ValidateOAuthToken(arg1:string,arg2:Record<string, string>):Promise<oauth.TokenValidationResult>;
