// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {logger} from '../models';

export function ClearLogs():Promise<void>;

export function CreateAccount(arg1:string,arg2:string,arg3:Record<string, string>):Promise<types.Account>;

export function CreateModelMapping(arg1:types.ModelMapping):Promise<void>;

export function CreateProvider(arg1:types.Provider):Promise<void>;

export function CreateSession(arg1:string,arg2:Array<types.ChatMessage>):Promise<types.SessionRecord>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetAccountsByProvider(arg1:string):Promise<Array<types.Account>>;

export function GetAllAccounts():Promise<Array<types.Account>>;

export function GetAllProviders():Promise<Array<types.Provider>>;

export function GetConfig():Promise<types.AppConfig>;

export function GetLogs(arg1:logger.LogOptions):Promise<Array<logger.LogEntry>>;

export function GetModelMappings():Promise<Array<types.ModelMapping>>;

export function GetProvider(arg1:string):Promise<types.Provider>;

export function GetProxyStatus():Promise<types.ProxyStatus>;

export function GetRequestLogs(arg1:number,arg2:number):Promise<Array<types.RequestLogEntry>>;

export function GetSession(arg1:string):Promise<types.SessionRecord>;

export function GetSessions():Promise<Array<types.SessionRecord>>;

export function GetStatistics():Promise<types.Statistics>;

export function StartProxy(arg1:number,arg2:string):Promise<boolean>;

export function StopProxy():Promise<boolean>;

export function UpdateAccount(arg1:string,arg2:Record<string, any>):Promise<void>;

export function UpdateConfig(arg1:types.AppConfig):Promise<void>;

export function UpdateModelMapping(arg1:string,arg2:Array<types.ModelMappingEntry>):Promise<void>;

export function UpdateProvider(arg1:string,arg2:Record<string, any>):Promise<void>;

export function UpdateSession(arg1:string,arg2:Array<types.ChatMessage>):Promise<void>;
